export const HEADING = {
    home: 'Home',
    aboutMe: 'About Me',
    highlights: 'Highlights',
    connect: 'Connect',
    language: 'Language',
    manualTopUp: 'Manual Top Up',
    delayedSettlement: 'Delayed Settlement',
    loo: 'Loo!',
    education: 'Education',
    clubs: 'Clubs',
    volunteer: 'Volunteering',
};

export const TEXT = {
  introduction: 'Hi, I\'m Kezia Liman',
  opening: 'Fresh grad software engineer based in Berkeley, CA',
  about_me_part_1a: 'The rapid rise of online applications has opened my eyes to the power of technology in elevating today\'s business. With my growing passion and eagerness to know more about this industry, I am taking Electrical Engineering and Computer Science as my major in ',
  about_me_part_1b: '. Outside of taking technical courses, I also took business and linear programming courses. My passion for business, which grew considerable stronger through studying different case studies both during IB and undergrad and my previous experience leading a food bazaar, is what motivates me to keep exploring the business tech industry. ',
  about_me_part_2a: 'I had 4 months internship experience for a ',
  about_me_part_2b: 'in Indonesia as a product engineer in the payment acceptance team.',
  about_me_part_3: 'I am currently looking for a full-time or internship as opportunities to hone my skills in software engineering, product engineering or any other business-tech fields!',
  more_projects: 'Explore More Projects',
  connect: 'Feel free to connect and reach out to me for any inquiries.',
  direct: 'Email: kezialiman@gmail.com  |  LinkedIn: Kezia Liman',
  oy_intern: 'Software Engineer Intern at OY!',
  loo_description: 'Personal Project: Android application used to search nearest restroom around you',
  berkeley: 'UC Berkeley 2019-2021',
  dvc: 'Diablo Valley College 2017-2019',
  women_in_stem: 'VP Women in STEM',
  secretary_earth_club: 'Secretary Earth Club',
  wtf_bazaar_1: 'Team Lead & Founder',
  wtf_bazaar_2: 'Where is The Food Bazaar',
  library: 'Children\'s Book Project',
  see_more: 'Click to see more information',

  bullet_points: {
    top_up_1: 'Developed manual top up feature with upload and download capabilities from AWS s3.',
    top_up_2: 'Implemented for update locking system using SQL.',
    top_up_3: 'Auto generated email and slack notification upon request submission.',
    top_up_4: 'Successfully prevent human error from previous one-way top up feature.',
    settlement_1: 'Built delayed settlement feature to solve liquidity issue with auto update capability using cron triggered scheduler.',
    settlement_2: 'Used SQL index to speed up filtering and sorting & export capability.',
    settlement_3: 'Testing in development server using Dbeaver and Postman.',
    loo_1: 'Developed using Android Studio and integrated toilet rating system using Firebase database.',
    loo_2: 'Implemented Google maps and Google sign-in API for user login.',
    loo_3: 'Designed UIUX using Figma and created user story flow chart.',
    gpa_berkeley: 'GPA: 3.72',
    gpa_dvc: 'GPA: 4.0',
    dsp_notetaker: 'DSP Note Taker',
    honors: 'Eta Kappa Nu (HKN) Honor\'s Society Member',
    dvc_math_tutor: 'DVC Math Tutor Algebra - Calculus III',
    women_awareness: 'Raised awareness on women who achieved great discoveries in STEM fields',
    workshop: 'Organized workshops and weekly meeting.',
    sign_up_volunteer: 'Created website for the club to ease volunteering sign up',
    bazaar_1: 'Food bazaar attended by 4000 people a day for 2 days.',
    bazaar_2: 'Closed agreement with 50 vendors & managed a team of 10 peers.',
    book_1: 'Build mini library & donated good second hand books.',
  },

  project_footer: {
    top_up: 'Java | Unit Test Junit & Mockito | Design Document | API Contract',
    settlement: 'Java | React | Design Document | API Contract | OOP Design',
    loo: 'CalHacks 2019 | Java | Figma',
  }
}

export const WEBLINK = {
  berkeley: 'https://eecs.berkeley.edu',
  oy: 'https://oyindonesia.com',
  github: 'https://github.com/kezialiman/project.git',
  linkedIn: 'https://www.linkedin.com/in/kezialiman',
  email: 'mailto:kezialiman@gmail.com',
  bazaar: 'https://suaraindonesia-news.com/sekolah-ciputra-menggelar-bazaar-wheres-the-food/',
}
